(define (problem task)
(:domain m-d-farmbot)
(:objects
    home a1 a2 a3 a4 a5 a6 a7 a8 a9 b1 b2 b3 b4 b5 b6 b7 b8 b9 seederpos wateringnozzlepos weederpos soilsensorpos posseedtray posbin - position
    carrot basil parsley - plant
    carrotseed basilseed parsleyseed - seed
    seeder wateringnozzle weeder soilsensor - tool
    seederrack wateringnozzlerack weederrack soilsensorrack - toolrack
    low high - level
    seedtray - container
    seedbin - bin
)
(:init
    (farmbot-functioning)


    (farmbot-at a4)

    (carry-tool weeder)

    (carry-camera)

    (tool-at seederpos seeder)
    (tool-at soilsensorpos soilsensor)
    (tool-at wateringnozzlepos wateringnozzle)

    (tool-rack-at seederrack seeder seederpos)
    (tool-rack-at wateringnozzlerack wateringnozzle wateringnozzlepos)
    (tool-rack-at weederrack weeder weederpos)
    (tool-rack-at soilsensorrack soilsensor soilsensorpos)

    (no-plant-at a5)
    (no-plant-at a6)
    (no-plant-at a7)
    (no-plant-at a8)
    (no-plant-at a9)
    (no-plant-at b5)
    (no-plant-at b6)
    (no-plant-at b7)
    (no-plant-at b8)
    (no-plant-at b9)

    (plant-at a1 carrot)
    (plant-at a2 carrot)
    (plant-at a3 carrot)
    (plant-at a4 carrot)
    (plant-at b1 carrot)
    (plant-at b2 carrot)
    (plant-at b3 carrot)
    (plant-at b4 carrot)



    (weed-removed b1)
    (weed-removed b2)
    (weed-removed b3)
    (weed-removed b4)
    (weed-removed a1)
    (weed-removed a2)
    (weed-removed a3)
    (weed-removed a4)



    (seeder-free)

    (container-at posseedtray seedtray)

    (container-has seedtray carrotseed)
    (container-has seedtray basilseed)
    (container-has seedtray parsleyseed)

    (match-seed-n-plant carrotseed carrot)
    (match-seed-n-plant basilseed basil)
    (match-seed-n-plant parsleyseed parsley)

    (bin-at posbin seedbin)




    (watered b1 carrot)
    (watered b2 carrot)
    (watered b3 carrot)
    (watered b4 carrot)
    (watered a1 carrot)
    (watered a2 carrot)
    (watered a3 carrot)
    (watered a4 carrot)

    (= (remaining-seed seedtray carrotseed) 10)
    (= (remaining-seed seedtray basilseed) 1)
    (= (remaining-seed seedtray parsleyseed) 1)

    (= (move-distance a1 a2) 2)
    (= (move-distance a1 a3) 4)
    (= (move-distance a1 a4) 5)
    (= (move-distance a1 a5) 7)
    (= (move-distance a1 a6) 9)
    (= (move-distance a1 a7) 10)
    (= (move-distance a1 a8) 12)
    (= (move-distance a1 a9) 14)
    (= (move-distance a1 b1) 6)
    (= (move-distance a1 b2) 8)
    (= (move-distance a1 b3) 10)
    (= (move-distance a1 b4) 11)
    (= (move-distance a1 b5) 13)
    (= (move-distance a1 b6) 15)
    (= (move-distance a1 b7) 16)
    (= (move-distance a1 b8) 18)
    (= (move-distance a1 b9) 20)
    (= (move-distance a1 seederpos) 5)
    (= (move-distance a1 wateringnozzlepos) 6)
    (= (move-distance a1 weederpos) 7)
    (= (move-distance a1 soilsensorpos) 8)
    (= (move-distance a1 posseedtray) 9)
    (= (move-distance a1 posbin) 10)
    (= (move-distance a1 home) 13)
    (= (move-distance a2 a1) 2)
    (= (move-distance a2 a3) 2)
    (= (move-distance a2 a4) 7)
    (= (move-distance a2 a5) 5)
    (= (move-distance a2 a6) 7)
    (= (move-distance a2 a7) 12)
    (= (move-distance a2 a8) 10)
    (= (move-distance a2 a9) 12)
    (= (move-distance a2 b1) 4)
    (= (move-distance a2 b2) 6)
    (= (move-distance a2 b3) 8)
    (= (move-distance a2 b4) 9)
    (= (move-distance a2 b5) 11)
    (= (move-distance a2 b6) 13)
    (= (move-distance a2 b7) 14)
    (= (move-distance a2 b8) 16)
    (= (move-distance a2 b9) 18)
    (= (move-distance a2 seederpos) 7)
    (= (move-distance a2 wateringnozzlepos) 8)
    (= (move-distance a2 weederpos) 9)
    (= (move-distance a2 soilsensorpos) 10)
    (= (move-distance a2 posseedtray) 11)
    (= (move-distance a2 posbin) 12)
    (= (move-distance a2 home) 11)
    (= (move-distance a3 a1) 4)
    (= (move-distance a3 a2) 2)
    (= (move-distance a3 a4) 9)
    (= (move-distance a3 a5) 7)
    (= (move-distance a3 a6) 5)
    (= (move-distance a3 a7) 14)
    (= (move-distance a3 a8) 12)
    (= (move-distance a3 a9) 10)
    (= (move-distance a3 b1) 2)
    (= (move-distance a3 b2) 4)
    (= (move-distance a3 b3) 6)
    (= (move-distance a3 b4) 7)
    (= (move-distance a3 b5) 9)
    (= (move-distance a3 b6) 11)
    (= (move-distance a3 b7) 12)
    (= (move-distance a3 b8) 14)
    (= (move-distance a3 b9) 16)
    (= (move-distance a3 seederpos) 9)
    (= (move-distance a3 wateringnozzlepos) 10)
    (= (move-distance a3 weederpos) 11)
    (= (move-distance a3 soilsensorpos) 12)
    (= (move-distance a3 posseedtray) 13)
    (= (move-distance a3 posbin) 14)
    (= (move-distance a3 home) 9)
    (= (move-distance a4 a1) 5)
    (= (move-distance a4 a2) 7)
    (= (move-distance a4 a3) 9)
    (= (move-distance a4 a5) 2)
    (= (move-distance a4 a6) 4)
    (= (move-distance a4 a7) 5)
    (= (move-distance a4 a8) 7)
    (= (move-distance a4 a9) 9)
    (= (move-distance a4 b1) 11)
    (= (move-distance a4 b2) 13)
    (= (move-distance a4 b3) 15)
    (= (move-distance a4 b4) 6)
    (= (move-distance a4 b5) 8)
    (= (move-distance a4 b6) 10)
    (= (move-distance a4 b7) 11)
    (= (move-distance a4 b8) 13)
    (= (move-distance a4 b9) 15)
    (= (move-distance a4 seederpos) 4)
    (= (move-distance a4 wateringnozzlepos) 3)
    (= (move-distance a4 weederpos) 2)
    (= (move-distance a4 soilsensorpos) 3)
    (= (move-distance a4 posseedtray) 4)
    (= (move-distance a4 posbin) 5)
    (= (move-distance a4 home) 8)
    (= (move-distance a5 a1) 7)
    (= (move-distance a5 a2) 5)
    (= (move-distance a5 a3) 7)
    (= (move-distance a5 a4) 2)
    (= (move-distance a5 a6) 2)
    (= (move-distance a5 a7) 7)
    (= (move-distance a5 a8) 5)
    (= (move-distance a5 a9) 7)
    (= (move-distance a5 b1) 9)
    (= (move-distance a5 b2) 11)
    (= (move-distance a5 b3) 13)
    (= (move-distance a5 b4) 4)
    (= (move-distance a5 b5) 6)
    (= (move-distance a5 b6) 8)
    (= (move-distance a5 b7) 9)
    (= (move-distance a5 b8) 11)
    (= (move-distance a5 b9) 13)
    (= (move-distance a5 seederpos) 6)
    (= (move-distance a5 wateringnozzlepos) 5)
    (= (move-distance a5 weederpos) 4)
    (= (move-distance a5 soilsensorpos) 5)
    (= (move-distance a5 posseedtray) 6)
    (= (move-distance a5 posbin) 7)
    (= (move-distance a5 home) 6)
    (= (move-distance a6 a1) 9)
    (= (move-distance a6 a2) 7)
    (= (move-distance a6 a3) 5)
    (= (move-distance a6 a4) 4)
    (= (move-distance a6 a5) 2)
    (= (move-distance a6 a7) 9)
    (= (move-distance a6 a8) 7)
    (= (move-distance a6 a9) 5)
    (= (move-distance a6 b1) 7)
    (= (move-distance a6 b2) 9)
    (= (move-distance a6 b3) 11)
    (= (move-distance a6 b4) 2)
    (= (move-distance a6 b5) 4)
    (= (move-distance a6 b6) 6)
    (= (move-distance a6 b7) 7)
    (= (move-distance a6 b8) 9)
    (= (move-distance a6 b9) 11)
    (= (move-distance a6 seederpos) 8)
    (= (move-distance a6 wateringnozzlepos) 7)
    (= (move-distance a6 weederpos) 6)
    (= (move-distance a6 soilsensorpos) 7)
    (= (move-distance a6 posseedtray) 8)
    (= (move-distance a6 posbin) 9)
    (= (move-distance a6 home) 4)
    (= (move-distance a7 a1) 10)
    (= (move-distance a7 a2) 12)
    (= (move-distance a7 a3) 14)
    (= (move-distance a7 a4) 5)
    (= (move-distance a7 a5) 7)
    (= (move-distance a7 a6) 9)
    (= (move-distance a7 a8) 2)
    (= (move-distance a7 a9) 4)
    (= (move-distance a7 b1) 16)
    (= (move-distance a7 b2) 18)
    (= (move-distance a7 b3) 20)
    (= (move-distance a7 b4) 11)
    (= (move-distance a7 b5) 13)
    (= (move-distance a7 b6) 15)
    (= (move-distance a7 b7) 6)
    (= (move-distance a7 b8) 8)
    (= (move-distance a7 b9) 10)
    (= (move-distance a7 seederpos) 9)
    (= (move-distance a7 wateringnozzlepos) 8)
    (= (move-distance a7 weederpos) 7)
    (= (move-distance a7 soilsensorpos) 6)
    (= (move-distance a7 posseedtray) 5)
    (= (move-distance a7 posbin) 4)
    (= (move-distance a7 home) 11)
    (= (move-distance a8 a1) 12)
    (= (move-distance a8 a2) 10)
    (= (move-distance a8 a3) 12)
    (= (move-distance a8 a4) 7)
    (= (move-distance a8 a5) 5)
    (= (move-distance a8 a6) 7)
    (= (move-distance a8 a7) 2)
    (= (move-distance a8 a9) 2)
    (= (move-distance a8 b1) 14)
    (= (move-distance a8 b2) 16)
    (= (move-distance a8 b3) 18)
    (= (move-distance a8 b4) 9)
    (= (move-distance a8 b5) 11)
    (= (move-distance a8 b6) 13)
    (= (move-distance a8 b7) 4)
    (= (move-distance a8 b8) 6)
    (= (move-distance a8 b9) 8)
    (= (move-distance a8 seederpos) 11)
    (= (move-distance a8 wateringnozzlepos) 10)
    (= (move-distance a8 weederpos) 9)
    (= (move-distance a8 soilsensorpos) 8)
    (= (move-distance a8 posseedtray) 7)
    (= (move-distance a8 posbin) 6)
    (= (move-distance a8 home) 9)
    (= (move-distance a9 a1) 14)
    (= (move-distance a9 a2) 12)
    (= (move-distance a9 a3) 10)
    (= (move-distance a9 a4) 9)
    (= (move-distance a9 a5) 7)
    (= (move-distance a9 a6) 5)
    (= (move-distance a9 a7) 4)
    (= (move-distance a9 a8) 2)
    (= (move-distance a9 b1) 12)
    (= (move-distance a9 b2) 14)
    (= (move-distance a9 b3) 16)
    (= (move-distance a9 b4) 7)
    (= (move-distance a9 b5) 9)
    (= (move-distance a9 b6) 11)
    (= (move-distance a9 b7) 2)
    (= (move-distance a9 b8) 4)
    (= (move-distance a9 b9) 6)
    (= (move-distance a9 seederpos) 13)
    (= (move-distance a9 wateringnozzlepos) 12)
    (= (move-distance a9 weederpos) 11)
    (= (move-distance a9 soilsensorpos) 10)
    (= (move-distance a9 posseedtray) 9)
    (= (move-distance a9 posbin) 8)
    (= (move-distance a9 home) 7)
    (= (move-distance b1 a1) 6)
    (= (move-distance b1 a2) 4)
    (= (move-distance b1 a3) 2)
    (= (move-distance b1 a4) 11)
    (= (move-distance b1 a5) 9)
    (= (move-distance b1 a6) 7)
    (= (move-distance b1 a7) 16)
    (= (move-distance b1 a8) 14)
    (= (move-distance b1 a9) 12)
    (= (move-distance b1 b2) 2)
    (= (move-distance b1 b3) 4)
    (= (move-distance b1 b4) 5)
    (= (move-distance b1 b5) 7)
    (= (move-distance b1 b6) 9)
    (= (move-distance b1 b7) 10)
    (= (move-distance b1 b8) 12)
    (= (move-distance b1 b9) 14)
    (= (move-distance b1 seederpos) 11)
    (= (move-distance b1 wateringnozzlepos) 12)
    (= (move-distance b1 weederpos) 13)
    (= (move-distance b1 soilsensorpos) 14)
    (= (move-distance b1 posseedtray) 15)
    (= (move-distance b1 posbin) 16)
    (= (move-distance b1 home) 7)
    (= (move-distance b2 a1) 8)
    (= (move-distance b2 a2) 6)
    (= (move-distance b2 a3) 4)
    (= (move-distance b2 a4) 13)
    (= (move-distance b2 a5) 11)
    (= (move-distance b2 a6) 9)
    (= (move-distance b2 a7) 18)
    (= (move-distance b2 a8) 16)
    (= (move-distance b2 a9) 14)
    (= (move-distance b2 b1) 2)
    (= (move-distance b2 b3) 2)
    (= (move-distance b2 b4) 7)
    (= (move-distance b2 b5) 5)
    (= (move-distance b2 b6) 7)
    (= (move-distance b2 b7) 12)
    (= (move-distance b2 b8) 10)
    (= (move-distance b2 b9) 12)
    (= (move-distance b2 seederpos) 13)
    (= (move-distance b2 wateringnozzlepos) 14)
    (= (move-distance b2 weederpos) 15)
    (= (move-distance b2 soilsensorpos) 16)
    (= (move-distance b2 posseedtray) 17)
    (= (move-distance b2 posbin) 18)
    (= (move-distance b2 home) 7)
    (= (move-distance b3 a1) 10)
    (= (move-distance b3 a2) 8)
    (= (move-distance b3 a3) 6)
    (= (move-distance b3 a4) 15)
    (= (move-distance b3 a5) 13)
    (= (move-distance b3 a6) 11)
    (= (move-distance b3 a7) 20)
    (= (move-distance b3 a8) 18)
    (= (move-distance b3 a9) 16)
    (= (move-distance b3 b1) 4)
    (= (move-distance b3 b2) 2)
    (= (move-distance b3 b4) 9)
    (= (move-distance b3 b5) 7)
    (= (move-distance b3 b6) 5)
    (= (move-distance b3 b7) 14)
    (= (move-distance b3 b8) 12)
    (= (move-distance b3 b9) 10)
    (= (move-distance b3 seederpos) 15)
    (= (move-distance b3 wateringnozzlepos) 16)
    (= (move-distance b3 weederpos) 17)
    (= (move-distance b3 soilsensorpos) 18)
    (= (move-distance b3 posseedtray) 19)
    (= (move-distance b3 posbin) 20)
    (= (move-distance b3 home) 9)
    (= (move-distance b4 a1) 11)
    (= (move-distance b4 a2) 9)
    (= (move-distance b4 a3) 7)
    (= (move-distance b4 a4) 6)
    (= (move-distance b4 a5) 4)
    (= (move-distance b4 a6) 2)
    (= (move-distance b4 a7) 11)
    (= (move-distance b4 a8) 9)
    (= (move-distance b4 a9) 7)
    (= (move-distance b4 b1) 5)
    (= (move-distance b4 b2) 7)
    (= (move-distance b4 b3) 9)
    (= (move-distance b4 b5) 2)
    (= (move-distance b4 b6) 4)
    (= (move-distance b4 b7) 5)
    (= (move-distance b4 b8) 7)
    (= (move-distance b4 b9) 9)
    (= (move-distance b4 seederpos) 10)
    (= (move-distance b4 wateringnozzlepos) 9)
    (= (move-distance b4 weederpos) 8)
    (= (move-distance b4 soilsensorpos) 9)
    (= (move-distance b4 posseedtray) 10)
    (= (move-distance b4 posbin) 11)
    (= (move-distance b4 home) 2)
    (= (move-distance b5 a1) 13)
    (= (move-distance b5 a2) 11)
    (= (move-distance b5 a3) 9)
    (= (move-distance b5 a4) 8)
    (= (move-distance b5 a5) 6)
    (= (move-distance b5 a6) 4)
    (= (move-distance b5 a7) 13)
    (= (move-distance b5 a8) 11)
    (= (move-distance b5 a9) 9)
    (= (move-distance b5 b1) 7)
    (= (move-distance b5 b2) 5)
    (= (move-distance b5 b3) 7)
    (= (move-distance b5 b4) 2)
    (= (move-distance b5 b6) 2)
    (= (move-distance b5 b7) 7)
    (= (move-distance b5 b8) 5)
    (= (move-distance b5 b9) 7)
    (= (move-distance b5 seederpos) 12)
    (= (move-distance b5 wateringnozzlepos) 11)
    (= (move-distance b5 weederpos) 10)
    (= (move-distance b5 soilsensorpos) 11)
    (= (move-distance b5 posseedtray) 12)
    (= (move-distance b5 posbin) 13)
    (= (move-distance b5 home) 2)
    (= (move-distance b6 a1) 15)
    (= (move-distance b6 a2) 13)
    (= (move-distance b6 a3) 11)
    (= (move-distance b6 a4) 10)
    (= (move-distance b6 a5) 8)
    (= (move-distance b6 a6) 6)
    (= (move-distance b6 a7) 15)
    (= (move-distance b6 a8) 13)
    (= (move-distance b6 a9) 11)
    (= (move-distance b6 b1) 9)
    (= (move-distance b6 b2) 7)
    (= (move-distance b6 b3) 5)
    (= (move-distance b6 b4) 4)
    (= (move-distance b6 b5) 2)
    (= (move-distance b6 b7) 9)
    (= (move-distance b6 b8) 7)
    (= (move-distance b6 b9) 5)
    (= (move-distance b6 seederpos) 14)
    (= (move-distance b6 wateringnozzlepos) 13)
    (= (move-distance b6 weederpos) 12)
    (= (move-distance b6 soilsensorpos) 13)
    (= (move-distance b6 posseedtray) 14)
    (= (move-distance b6 posbin) 15)
    (= (move-distance b6 home) 4)
    (= (move-distance b7 a1) 16)
    (= (move-distance b7 a2) 14)
    (= (move-distance b7 a3) 12)
    (= (move-distance b7 a4) 11)
    (= (move-distance b7 a5) 9)
    (= (move-distance b7 a6) 7)
    (= (move-distance b7 a7) 6)
    (= (move-distance b7 a8) 4)
    (= (move-distance b7 a9) 2)
    (= (move-distance b7 b1) 10)
    (= (move-distance b7 b2) 12)
    (= (move-distance b7 b3) 14)
    (= (move-distance b7 b4) 5)
    (= (move-distance b7 b5) 7)
    (= (move-distance b7 b6) 9)
    (= (move-distance b7 b8) 2)
    (= (move-distance b7 b9) 4)
    (= (move-distance b7 seederpos) 15)
    (= (move-distance b7 wateringnozzlepos) 14)
    (= (move-distance b7 weederpos) 13)
    (= (move-distance b7 soilsensorpos) 12)
    (= (move-distance b7 posseedtray) 11)
    (= (move-distance b7 posbin) 10)
    (= (move-distance b7 home) 5)
    (= (move-distance b8 a1) 18)
    (= (move-distance b8 a2) 16)
    (= (move-distance b8 a3) 14)
    (= (move-distance b8 a4) 13)
    (= (move-distance b8 a5) 11)
    (= (move-distance b8 a6) 9)
    (= (move-distance b8 a7) 8)
    (= (move-distance b8 a8) 6)
    (= (move-distance b8 a9) 4)
    (= (move-distance b8 b1) 12)
    (= (move-distance b8 b2) 10)
    (= (move-distance b8 b3) 12)
    (= (move-distance b8 b4) 7)
    (= (move-distance b8 b5) 5)
    (= (move-distance b8 b6) 7)
    (= (move-distance b8 b7) 2)
    (= (move-distance b8 b9) 2)
    (= (move-distance b8 seederpos) 17)
    (= (move-distance b8 wateringnozzlepos) 16)
    (= (move-distance b8 weederpos) 15)
    (= (move-distance b8 soilsensorpos) 14)
    (= (move-distance b8 posseedtray) 13)
    (= (move-distance b8 posbin) 12)
    (= (move-distance b8 home) 5)
    (= (move-distance b9 a1) 20)
    (= (move-distance b9 a2) 18)
    (= (move-distance b9 a3) 16)
    (= (move-distance b9 a4) 15)
    (= (move-distance b9 a5) 13)
    (= (move-distance b9 a6) 11)
    (= (move-distance b9 a7) 10)
    (= (move-distance b9 a8) 8)
    (= (move-distance b9 a9) 6)
    (= (move-distance b9 b1) 14)
    (= (move-distance b9 b2) 12)
    (= (move-distance b9 b3) 10)
    (= (move-distance b9 b4) 9)
    (= (move-distance b9 b5) 7)
    (= (move-distance b9 b6) 5)
    (= (move-distance b9 b7) 4)
    (= (move-distance b9 b8) 2)
    (= (move-distance b9 seederpos) 19)
    (= (move-distance b9 wateringnozzlepos) 18)
    (= (move-distance b9 weederpos) 17)
    (= (move-distance b9 soilsensorpos) 16)
    (= (move-distance b9 posseedtray) 15)
    (= (move-distance b9 posbin) 14)
    (= (move-distance b9 home) 7)
    (= (move-distance seederpos a1) 5)
    (= (move-distance seederpos a2) 7)
    (= (move-distance seederpos a3) 9)
    (= (move-distance seederpos a4) 4)
    (= (move-distance seederpos a5) 6)
    (= (move-distance seederpos a6) 8)
    (= (move-distance seederpos a7) 9)
    (= (move-distance seederpos a8) 11)
    (= (move-distance seederpos a9) 13)
    (= (move-distance seederpos b1) 11)
    (= (move-distance seederpos b2) 13)
    (= (move-distance seederpos b3) 15)
    (= (move-distance seederpos b4) 10)
    (= (move-distance seederpos b5) 12)
    (= (move-distance seederpos b6) 14)
    (= (move-distance seederpos b7) 15)
    (= (move-distance seederpos b8) 17)
    (= (move-distance seederpos b9) 19)
    (= (move-distance seederpos wateringnozzlepos) 1)
    (= (move-distance seederpos weederpos) 2)
    (= (move-distance seederpos soilsensorpos) 3)
    (= (move-distance seederpos posseedtray) 4)
    (= (move-distance seederpos posbin) 5)
    (= (move-distance seederpos home) 12)
    (= (move-distance wateringnozzlepos a1) 6)
    (= (move-distance wateringnozzlepos a2) 8)
    (= (move-distance wateringnozzlepos a3) 10)
    (= (move-distance wateringnozzlepos a4) 3)
    (= (move-distance wateringnozzlepos a5) 5)
    (= (move-distance wateringnozzlepos a6) 7)
    (= (move-distance wateringnozzlepos a7) 8)
    (= (move-distance wateringnozzlepos a8) 10)
    (= (move-distance wateringnozzlepos a9) 12)
    (= (move-distance wateringnozzlepos b1) 12)
    (= (move-distance wateringnozzlepos b2) 14)
    (= (move-distance wateringnozzlepos b3) 16)
    (= (move-distance wateringnozzlepos b4) 9)
    (= (move-distance wateringnozzlepos b5) 11)
    (= (move-distance wateringnozzlepos b6) 13)
    (= (move-distance wateringnozzlepos b7) 14)
    (= (move-distance wateringnozzlepos b8) 16)
    (= (move-distance wateringnozzlepos b9) 18)
    (= (move-distance wateringnozzlepos seederpos) 1)
    (= (move-distance wateringnozzlepos weederpos) 1)
    (= (move-distance wateringnozzlepos soilsensorpos) 2)
    (= (move-distance wateringnozzlepos posseedtray) 3)
    (= (move-distance wateringnozzlepos posbin) 4)
    (= (move-distance wateringnozzlepos home) 11)
    (= (move-distance weederpos a1) 7)
    (= (move-distance weederpos a2) 9)
    (= (move-distance weederpos a3) 11)
    (= (move-distance weederpos a4) 2)
    (= (move-distance weederpos a5) 4)
    (= (move-distance weederpos a6) 6)
    (= (move-distance weederpos a7) 7)
    (= (move-distance weederpos a8) 9)
    (= (move-distance weederpos a9) 11)
    (= (move-distance weederpos b1) 13)
    (= (move-distance weederpos b2) 15)
    (= (move-distance weederpos b3) 17)
    (= (move-distance weederpos b4) 8)
    (= (move-distance weederpos b5) 10)
    (= (move-distance weederpos b6) 12)
    (= (move-distance weederpos b7) 13)
    (= (move-distance weederpos b8) 15)
    (= (move-distance weederpos b9) 17)
    (= (move-distance weederpos seederpos) 2)
    (= (move-distance weederpos wateringnozzlepos) 1)
    (= (move-distance weederpos soilsensorpos) 1)
    (= (move-distance weederpos posseedtray) 2)
    (= (move-distance weederpos posbin) 3)
    (= (move-distance weederpos home) 10)
    (= (move-distance soilsensorpos a1) 8)
    (= (move-distance soilsensorpos a2) 10)
    (= (move-distance soilsensorpos a3) 12)
    (= (move-distance soilsensorpos a4) 3)
    (= (move-distance soilsensorpos a5) 5)
    (= (move-distance soilsensorpos a6) 7)
    (= (move-distance soilsensorpos a7) 6)
    (= (move-distance soilsensorpos a8) 8)
    (= (move-distance soilsensorpos a9) 10)
    (= (move-distance soilsensorpos b1) 14)
    (= (move-distance soilsensorpos b2) 16)
    (= (move-distance soilsensorpos b3) 18)
    (= (move-distance soilsensorpos b4) 9)
    (= (move-distance soilsensorpos b5) 11)
    (= (move-distance soilsensorpos b6) 13)
    (= (move-distance soilsensorpos b7) 12)
    (= (move-distance soilsensorpos b8) 14)
    (= (move-distance soilsensorpos b9) 16)
    (= (move-distance soilsensorpos seederpos) 3)
    (= (move-distance soilsensorpos wateringnozzlepos) 2)
    (= (move-distance soilsensorpos weederpos) 1)
    (= (move-distance soilsensorpos posseedtray) 1)
    (= (move-distance soilsensorpos posbin) 2)
    (= (move-distance soilsensorpos home) 9)
    (= (move-distance posseedtray a1) 9)
    (= (move-distance posseedtray a2) 11)
    (= (move-distance posseedtray a3) 13)
    (= (move-distance posseedtray a4) 4)
    (= (move-distance posseedtray a5) 6)
    (= (move-distance posseedtray a6) 8)
    (= (move-distance posseedtray a7) 5)
    (= (move-distance posseedtray a8) 7)
    (= (move-distance posseedtray a9) 9)
    (= (move-distance posseedtray b1) 15)
    (= (move-distance posseedtray b2) 17)
    (= (move-distance posseedtray b3) 19)
    (= (move-distance posseedtray b4) 10)
    (= (move-distance posseedtray b5) 12)
    (= (move-distance posseedtray b6) 14)
    (= (move-distance posseedtray b7) 11)
    (= (move-distance posseedtray b8) 13)
    (= (move-distance posseedtray b9) 15)
    (= (move-distance posseedtray seederpos) 4)
    (= (move-distance posseedtray wateringnozzlepos) 3)
    (= (move-distance posseedtray weederpos) 2)
    (= (move-distance posseedtray soilsensorpos) 1)
    (= (move-distance posseedtray posbin) 1)
    (= (move-distance posseedtray home) 10)
    (= (move-distance posbin a1) 10)
    (= (move-distance posbin a2) 12)
    (= (move-distance posbin a3) 14)
    (= (move-distance posbin a4) 5)
    (= (move-distance posbin a5) 7)
    (= (move-distance posbin a6) 9)
    (= (move-distance posbin a7) 4)
    (= (move-distance posbin a8) 6)
    (= (move-distance posbin a9) 8)
    (= (move-distance posbin b1) 16)
    (= (move-distance posbin b2) 18)
    (= (move-distance posbin b3) 20)
    (= (move-distance posbin b4) 11)
    (= (move-distance posbin b5) 13)
    (= (move-distance posbin b6) 15)
    (= (move-distance posbin b7) 10)
    (= (move-distance posbin b8) 12)
    (= (move-distance posbin b9) 14)
    (= (move-distance posbin seederpos) 5)
    (= (move-distance posbin wateringnozzlepos) 4)
    (= (move-distance posbin weederpos) 3)
    (= (move-distance posbin soilsensorpos) 2)
    (= (move-distance posbin posseedtray) 1)
    (= (move-distance posbin home) 11)
    (= (move-distance home a1) 13)
    (= (move-distance home a2) 11)
    (= (move-distance home a3) 9)
    (= (move-distance home a4) 8)
    (= (move-distance home a5) 6)
    (= (move-distance home a6) 4)
    (= (move-distance home a7) 11)
    (= (move-distance home a8) 9)
    (= (move-distance home a9) 7)
    (= (move-distance home b1) 7)
    (= (move-distance home b2) 7)
    (= (move-distance home b3) 9)
    (= (move-distance home b4) 2)
    (= (move-distance home b5) 2)
    (= (move-distance home b6) 4)
    (= (move-distance home b7) 5)
    (= (move-distance home b8) 5)
    (= (move-distance home b9) 7)
    (= (move-distance home seederpos) 12)
    (= (move-distance home wateringnozzlepos) 11)
    (= (move-distance home weederpos) 10)
    (= (move-distance home soilsensorpos) 9)
    (= (move-distance home posseedtray) 10)
    (= (move-distance home posbin) 11)

    (= (total-moving-cost) 0)

)
(:goal (and
    (checked-moisture b1 carrot)
    (checked-moisture b2 carrot)
    (checked-moisture b3 carrot)
    (checked-moisture b4 carrot)
    (checked-moisture a1 carrot)
    (checked-moisture a2 carrot)
    (checked-moisture a3 carrot)
    (checked-moisture a4 carrot)
))
(:metric minimize (total-moving-cost))
)
