(define (problem initial-state) (:domain m-d-farmbot)
(:objects 
    home A1 A2 A3 A4 A5 A6 A7 A8 A9 B1 B2 B3 B4 B5 B6 B7 B8 B9 - position
    carrotSeed basilSeed parsleySeed - seed
    carrot basil parsley - plant
)

(:init

    ;(farmbot-functioning)
    (farmbot-at home)
    (carry-camera)
    (tool-mount-free)
    (seeder-free)

    (tool-rack-at seederrack seeder seederPos)
    (tool-rack-at wateringnozzlerack wateringnozzle wateringnozzlePos)
    (tool-rack-at weederrack weeder weederPos)
    (tool-rack-at soilsensorrack soilsensor soilsensorPos)

    (tool-at seederPos seeder)
    (tool-at wateringnozzlePos wateringnozzle)
    (tool-at weederPos weeder)
    (tool-at soilsensorPos soilsensor)

    (container-at posSeedTray seedtray)
    (container-has seedtray carrotSeed)                              
    (container-has seedtray basilSeed)
    (container-has seedtray parsleySeed)

    (= (remaining-seed seedtray carrotSeed) 10)
    (= (remaining-seed seedtray basilSeed) 1)
    (= (remaining-seed seedtray parsleySeed) 1)
    (= (total-moving-cost) 0)

    (bin-at posBin seedbin)

    (match-seed-n-plant carrotSeed carrot)
    (match-seed-n-plant basilSeed basil)
    (match-seed-n-plant parsleySeed parsley)

    (no-plant-at A1)
    (no-plant-at A2)
    (no-plant-at A3)
    (no-plant-at A4)
    (no-plant-at A5)
    (no-plant-at A6)
    (no-plant-at A7)
    (no-plant-at A8)
    (no-plant-at A9)

    (no-plant-at B1)
    (no-plant-at B2)
    (no-plant-at B3)
    (no-plant-at B4)
    (no-plant-at B5)
    (no-plant-at B6)
    (no-plant-at B7)
    (no-plant-at B8)
    (no-plant-at B9)

    (= (move-distance A1 A2) 2)
    (= (move-distance A1 A3) 4)
    (= (move-distance A1 A4) 5)
    (= (move-distance A1 A5) 7)
    (= (move-distance A1 A6) 9)
    (= (move-distance A1 A7) 10)
    (= (move-distance A1 A8) 12)
    (= (move-distance A1 A9) 14)
    (= (move-distance A1 B1) 6)
    (= (move-distance A1 B2) 8)
    (= (move-distance A1 B3) 10)
    (= (move-distance A1 B4) 11)
    (= (move-distance A1 B5) 13)
    (= (move-distance A1 B6) 15)
    (= (move-distance A1 B7) 16)
    (= (move-distance A1 B8) 18)
    (= (move-distance A1 B9) 20)
    (= (move-distance A1 seederPos) 5)
    (= (move-distance A1 wateringnozzlePos) 6)
    (= (move-distance A1 weederPos) 7)
    (= (move-distance A1 soilsensorPos) 8)
    (= (move-distance A1 posSeedTray) 9)
    (= (move-distance A1 posBin) 10)
    (= (move-distance A1 home) 13)
    (= (move-distance A2 A1) 2)
    (= (move-distance A2 A3) 2)
    (= (move-distance A2 A4) 7)
    (= (move-distance A2 A5) 5)
    (= (move-distance A2 A6) 7)
    (= (move-distance A2 A7) 12)
    (= (move-distance A2 A8) 10)
    (= (move-distance A2 A9) 12)
    (= (move-distance A2 B1) 4)
    (= (move-distance A2 B2) 6)
    (= (move-distance A2 B3) 8)
    (= (move-distance A2 B4) 9)
    (= (move-distance A2 B5) 11)
    (= (move-distance A2 B6) 13)
    (= (move-distance A2 B7) 14)
    (= (move-distance A2 B8) 16)
    (= (move-distance A2 B9) 18)
    (= (move-distance A2 seederPos) 7)
    (= (move-distance A2 wateringnozzlePos) 8)
    (= (move-distance A2 weederPos) 9)
    (= (move-distance A2 soilsensorPos) 10)
    (= (move-distance A2 posSeedTray) 11)
    (= (move-distance A2 posBin) 12)
    (= (move-distance A2 home) 11)
    (= (move-distance A3 A1) 4)
    (= (move-distance A3 A2) 2)
    (= (move-distance A3 A4) 9)
    (= (move-distance A3 A5) 7)
    (= (move-distance A3 A6) 5)
    (= (move-distance A3 A7) 14)
    (= (move-distance A3 A8) 12)
    (= (move-distance A3 A9) 10)
    (= (move-distance A3 B1) 2)
    (= (move-distance A3 B2) 4)
    (= (move-distance A3 B3) 6)
    (= (move-distance A3 B4) 7)
    (= (move-distance A3 B5) 9)
    (= (move-distance A3 B6) 11)
    (= (move-distance A3 B7) 12)
    (= (move-distance A3 B8) 14)
    (= (move-distance A3 B9) 16)
    (= (move-distance A3 seederPos) 9)
    (= (move-distance A3 wateringnozzlePos) 10)
    (= (move-distance A3 weederPos) 11)
    (= (move-distance A3 soilsensorPos) 12)
    (= (move-distance A3 posSeedTray) 13)
    (= (move-distance A3 posBin) 14)
    (= (move-distance A3 home) 9)
    (= (move-distance A4 A1) 5)
    (= (move-distance A4 A2) 7)
    (= (move-distance A4 A3) 9)
    (= (move-distance A4 A5) 2)
    (= (move-distance A4 A6) 4)
    (= (move-distance A4 A7) 5)
    (= (move-distance A4 A8) 7)
    (= (move-distance A4 A9) 9)
    (= (move-distance A4 B1) 11)
    (= (move-distance A4 B2) 13)
    (= (move-distance A4 B3) 15)
    (= (move-distance A4 B4) 6)
    (= (move-distance A4 B5) 8)
    (= (move-distance A4 B6) 10)
    (= (move-distance A4 B7) 11)
    (= (move-distance A4 B8) 13)
    (= (move-distance A4 B9) 15)
    (= (move-distance A4 seederPos) 4)
    (= (move-distance A4 wateringnozzlePos) 3)
    (= (move-distance A4 weederPos) 2)
    (= (move-distance A4 soilsensorPos) 3)
    (= (move-distance A4 posSeedTray) 4)
    (= (move-distance A4 posBin) 5)
    (= (move-distance A4 home) 8)
    (= (move-distance A5 A1) 7)
    (= (move-distance A5 A2) 5)
    (= (move-distance A5 A3) 7)
    (= (move-distance A5 A4) 2)
    (= (move-distance A5 A6) 2)
    (= (move-distance A5 A7) 7)
    (= (move-distance A5 A8) 5)
    (= (move-distance A5 A9) 7)
    (= (move-distance A5 B1) 9)
    (= (move-distance A5 B2) 11)
    (= (move-distance A5 B3) 13)
    (= (move-distance A5 B4) 4)
    (= (move-distance A5 B5) 6)
    (= (move-distance A5 B6) 8)
    (= (move-distance A5 B7) 9)
    (= (move-distance A5 B8) 11)
    (= (move-distance A5 B9) 13)
    (= (move-distance A5 seederPos) 6)
    (= (move-distance A5 wateringnozzlePos) 5)
    (= (move-distance A5 weederPos) 4)
    (= (move-distance A5 soilsensorPos) 5)
    (= (move-distance A5 posSeedTray) 6)
    (= (move-distance A5 posBin) 7)
    (= (move-distance A5 home) 6)
    (= (move-distance A6 A1) 9)
    (= (move-distance A6 A2) 7)
    (= (move-distance A6 A3) 5)
    (= (move-distance A6 A4) 4)
    (= (move-distance A6 A5) 2)
    (= (move-distance A6 A7) 9)
    (= (move-distance A6 A8) 7)
    (= (move-distance A6 A9) 5)
    (= (move-distance A6 B1) 7)
    (= (move-distance A6 B2) 9)
    (= (move-distance A6 B3) 11)
    (= (move-distance A6 B4) 2)
    (= (move-distance A6 B5) 4)
    (= (move-distance A6 B6) 6)
    (= (move-distance A6 B7) 7)
    (= (move-distance A6 B8) 9)
    (= (move-distance A6 B9) 11)
    (= (move-distance A6 seederPos) 8)
    (= (move-distance A6 wateringnozzlePos) 7)
    (= (move-distance A6 weederPos) 6)
    (= (move-distance A6 soilsensorPos) 7)
    (= (move-distance A6 posSeedTray) 8)
    (= (move-distance A6 posBin) 9)
    (= (move-distance A6 home) 4)
    (= (move-distance A7 A1) 10)
    (= (move-distance A7 A2) 12)
    (= (move-distance A7 A3) 14)
    (= (move-distance A7 A4) 5)
    (= (move-distance A7 A5) 7)
    (= (move-distance A7 A6) 9)
    (= (move-distance A7 A8) 2)
    (= (move-distance A7 A9) 4)
    (= (move-distance A7 B1) 16)
    (= (move-distance A7 B2) 18)
    (= (move-distance A7 B3) 20)
    (= (move-distance A7 B4) 11)
    (= (move-distance A7 B5) 13)
    (= (move-distance A7 B6) 15)
    (= (move-distance A7 B7) 6)
    (= (move-distance A7 B8) 8)
    (= (move-distance A7 B9) 10)
    (= (move-distance A7 seederPos) 9)
    (= (move-distance A7 wateringnozzlePos) 8)
    (= (move-distance A7 weederPos) 7)
    (= (move-distance A7 soilsensorPos) 6)
    (= (move-distance A7 posSeedTray) 5)
    (= (move-distance A7 posBin) 4)
    (= (move-distance A7 home) 11)
    (= (move-distance A8 A1) 12)
    (= (move-distance A8 A2) 10)
    (= (move-distance A8 A3) 12)
    (= (move-distance A8 A4) 7)
    (= (move-distance A8 A5) 5)
    (= (move-distance A8 A6) 7)
    (= (move-distance A8 A7) 2)
    (= (move-distance A8 A9) 2)
    (= (move-distance A8 B1) 14)
    (= (move-distance A8 B2) 16)
    (= (move-distance A8 B3) 18)
    (= (move-distance A8 B4) 9)
    (= (move-distance A8 B5) 11)
    (= (move-distance A8 B6) 13)
    (= (move-distance A8 B7) 4)
    (= (move-distance A8 B8) 6)
    (= (move-distance A8 B9) 8)
    (= (move-distance A8 seederPos) 11)
    (= (move-distance A8 wateringnozzlePos) 10)
    (= (move-distance A8 weederPos) 9)
    (= (move-distance A8 soilsensorPos) 8)
    (= (move-distance A8 posSeedTray) 7)
    (= (move-distance A8 posBin) 6)
    (= (move-distance A8 home) 9)
    (= (move-distance A9 A1) 14)
    (= (move-distance A9 A2) 12)
    (= (move-distance A9 A3) 10)
    (= (move-distance A9 A4) 9)
    (= (move-distance A9 A5) 7)
    (= (move-distance A9 A6) 5)
    (= (move-distance A9 A7) 4)
    (= (move-distance A9 A8) 2)
    (= (move-distance A9 B1) 12)
    (= (move-distance A9 B2) 14)
    (= (move-distance A9 B3) 16)
    (= (move-distance A9 B4) 7)
    (= (move-distance A9 B5) 9)
    (= (move-distance A9 B6) 11)
    (= (move-distance A9 B7) 2)
    (= (move-distance A9 B8) 4)
    (= (move-distance A9 B9) 6)
    (= (move-distance A9 seederPos) 13)
    (= (move-distance A9 wateringnozzlePos) 12)
    (= (move-distance A9 weederPos) 11)
    (= (move-distance A9 soilsensorPos) 10)
    (= (move-distance A9 posSeedTray) 9)
    (= (move-distance A9 posBin) 8)
    (= (move-distance A9 home) 7)
    (= (move-distance B1 A1) 6)
    (= (move-distance B1 A2) 4)
    (= (move-distance B1 A3) 2)
    (= (move-distance B1 A4) 11)
    (= (move-distance B1 A5) 9)
    (= (move-distance B1 A6) 7)
    (= (move-distance B1 A7) 16)
    (= (move-distance B1 A8) 14)
    (= (move-distance B1 A9) 12)
    (= (move-distance B1 B2) 2)
    (= (move-distance B1 B3) 4)
    (= (move-distance B1 B4) 5)
    (= (move-distance B1 B5) 7)
    (= (move-distance B1 B6) 9)
    (= (move-distance B1 B7) 10)
    (= (move-distance B1 B8) 12)
    (= (move-distance B1 B9) 14)
    (= (move-distance B1 seederPos) 11)
    (= (move-distance B1 wateringnozzlePos) 12)
    (= (move-distance B1 weederPos) 13)
    (= (move-distance B1 soilsensorPos) 14)
    (= (move-distance B1 posSeedTray) 15)
    (= (move-distance B1 posBin) 16)
    (= (move-distance B1 home) 7)
    (= (move-distance B2 A1) 8)
    (= (move-distance B2 A2) 6)
    (= (move-distance B2 A3) 4)
    (= (move-distance B2 A4) 13)
    (= (move-distance B2 A5) 11)
    (= (move-distance B2 A6) 9)
    (= (move-distance B2 A7) 18)
    (= (move-distance B2 A8) 16)
    (= (move-distance B2 A9) 14)
    (= (move-distance B2 B1) 2)
    (= (move-distance B2 B3) 2)
    (= (move-distance B2 B4) 7)
    (= (move-distance B2 B5) 5)
    (= (move-distance B2 B6) 7)
    (= (move-distance B2 B7) 12)
    (= (move-distance B2 B8) 10)
    (= (move-distance B2 B9) 12)
    (= (move-distance B2 seederPos) 13)
    (= (move-distance B2 wateringnozzlePos) 14)
    (= (move-distance B2 weederPos) 15)
    (= (move-distance B2 soilsensorPos) 16)
    (= (move-distance B2 posSeedTray) 17)
    (= (move-distance B2 posBin) 18)
    (= (move-distance B2 home) 7)
    (= (move-distance B3 A1) 10)
    (= (move-distance B3 A2) 8)
    (= (move-distance B3 A3) 6)
    (= (move-distance B3 A4) 15)
    (= (move-distance B3 A5) 13)
    (= (move-distance B3 A6) 11)
    (= (move-distance B3 A7) 20)
    (= (move-distance B3 A8) 18)
    (= (move-distance B3 A9) 16)
    (= (move-distance B3 B1) 4)
    (= (move-distance B3 B2) 2)
    (= (move-distance B3 B4) 9)
    (= (move-distance B3 B5) 7)
    (= (move-distance B3 B6) 5)
    (= (move-distance B3 B7) 14)
    (= (move-distance B3 B8) 12)
    (= (move-distance B3 B9) 10)
    (= (move-distance B3 seederPos) 15)
    (= (move-distance B3 wateringnozzlePos) 16)
    (= (move-distance B3 weederPos) 17)
    (= (move-distance B3 soilsensorPos) 18)
    (= (move-distance B3 posSeedTray) 19)
    (= (move-distance B3 posBin) 20)
    (= (move-distance B3 home) 9)
    (= (move-distance B4 A1) 11)
    (= (move-distance B4 A2) 9)
    (= (move-distance B4 A3) 7)
    (= (move-distance B4 A4) 6)
    (= (move-distance B4 A5) 4)
    (= (move-distance B4 A6) 2)
    (= (move-distance B4 A7) 11)
    (= (move-distance B4 A8) 9)
    (= (move-distance B4 A9) 7)
    (= (move-distance B4 B1) 5)
    (= (move-distance B4 B2) 7)
    (= (move-distance B4 B3) 9)
    (= (move-distance B4 B5) 2)
    (= (move-distance B4 B6) 4)
    (= (move-distance B4 B7) 5)
    (= (move-distance B4 B8) 7)
    (= (move-distance B4 B9) 9)
    (= (move-distance B4 seederPos) 10)
    (= (move-distance B4 wateringnozzlePos) 9)
    (= (move-distance B4 weederPos) 8)
    (= (move-distance B4 soilsensorPos) 9)
    (= (move-distance B4 posSeedTray) 10)
    (= (move-distance B4 posBin) 11)
    (= (move-distance B4 home) 2)
    (= (move-distance B5 A1) 13)
    (= (move-distance B5 A2) 11)
    (= (move-distance B5 A3) 9)
    (= (move-distance B5 A4) 8)
    (= (move-distance B5 A5) 6)
    (= (move-distance B5 A6) 4)
    (= (move-distance B5 A7) 13)
    (= (move-distance B5 A8) 11)
    (= (move-distance B5 A9) 9)
    (= (move-distance B5 B1) 7)
    (= (move-distance B5 B2) 5)
    (= (move-distance B5 B3) 7)
    (= (move-distance B5 B4) 2)
    (= (move-distance B5 B6) 2)
    (= (move-distance B5 B7) 7)
    (= (move-distance B5 B8) 5)
    (= (move-distance B5 B9) 7)
    (= (move-distance B5 seederPos) 12)
    (= (move-distance B5 wateringnozzlePos) 11)
    (= (move-distance B5 weederPos) 10)
    (= (move-distance B5 soilsensorPos) 11)
    (= (move-distance B5 posSeedTray) 12)
    (= (move-distance B5 posBin) 13)
    (= (move-distance B5 home) 2)
    (= (move-distance B6 A1) 15)
    (= (move-distance B6 A2) 13)
    (= (move-distance B6 A3) 11)
    (= (move-distance B6 A4) 10)
    (= (move-distance B6 A5) 8)
    (= (move-distance B6 A6) 6)
    (= (move-distance B6 A7) 15)
    (= (move-distance B6 A8) 13)
    (= (move-distance B6 A9) 11)
    (= (move-distance B6 B1) 9)
    (= (move-distance B6 B2) 7)
    (= (move-distance B6 B3) 5)
    (= (move-distance B6 B4) 4)
    (= (move-distance B6 B5) 2)
    (= (move-distance B6 B7) 9)
    (= (move-distance B6 B8) 7)
    (= (move-distance B6 B9) 5)
    (= (move-distance B6 seederPos) 14)
    (= (move-distance B6 wateringnozzlePos) 13)
    (= (move-distance B6 weederPos) 12)
    (= (move-distance B6 soilsensorPos) 13)
    (= (move-distance B6 posSeedTray) 14)
    (= (move-distance B6 posBin) 15)
    (= (move-distance B6 home) 4)
    (= (move-distance B7 A1) 16)
    (= (move-distance B7 A2) 14)
    (= (move-distance B7 A3) 12)
    (= (move-distance B7 A4) 11)
    (= (move-distance B7 A5) 9)
    (= (move-distance B7 A6) 7)
    (= (move-distance B7 A7) 6)
    (= (move-distance B7 A8) 4)
    (= (move-distance B7 A9) 2)
    (= (move-distance B7 B1) 10)
    (= (move-distance B7 B2) 12)
    (= (move-distance B7 B3) 14)
    (= (move-distance B7 B4) 5)
    (= (move-distance B7 B5) 7)
    (= (move-distance B7 B6) 9)
    (= (move-distance B7 B8) 2)
    (= (move-distance B7 B9) 4)
    (= (move-distance B7 seederPos) 15)
    (= (move-distance B7 wateringnozzlePos) 14)
    (= (move-distance B7 weederPos) 13)
    (= (move-distance B7 soilsensorPos) 12)
    (= (move-distance B7 posSeedTray) 11)
    (= (move-distance B7 posBin) 10)
    (= (move-distance B7 home) 5)
    (= (move-distance B8 A1) 18)
    (= (move-distance B8 A2) 16)
    (= (move-distance B8 A3) 14)
    (= (move-distance B8 A4) 13)
    (= (move-distance B8 A5) 11)
    (= (move-distance B8 A6) 9)
    (= (move-distance B8 A7) 8)
    (= (move-distance B8 A8) 6)
    (= (move-distance B8 A9) 4)
    (= (move-distance B8 B1) 12)
    (= (move-distance B8 B2) 10)
    (= (move-distance B8 B3) 12)
    (= (move-distance B8 B4) 7)
    (= (move-distance B8 B5) 5)
    (= (move-distance B8 B6) 7)
    (= (move-distance B8 B7) 2)
    (= (move-distance B8 B9) 2)
    (= (move-distance B8 seederPos) 17)
    (= (move-distance B8 wateringnozzlePos) 16)
    (= (move-distance B8 weederPos) 15)
    (= (move-distance B8 soilsensorPos) 14)
    (= (move-distance B8 posSeedTray) 13)
    (= (move-distance B8 posBin) 12)
    (= (move-distance B8 home) 5)
    (= (move-distance B9 A1) 20)
    (= (move-distance B9 A2) 18)
    (= (move-distance B9 A3) 16)
    (= (move-distance B9 A4) 15)
    (= (move-distance B9 A5) 13)
    (= (move-distance B9 A6) 11)
    (= (move-distance B9 A7) 10)
    (= (move-distance B9 A8) 8)
    (= (move-distance B9 A9) 6)
    (= (move-distance B9 B1) 14)
    (= (move-distance B9 B2) 12)
    (= (move-distance B9 B3) 10)
    (= (move-distance B9 B4) 9)
    (= (move-distance B9 B5) 7)
    (= (move-distance B9 B6) 5)
    (= (move-distance B9 B7) 4)
    (= (move-distance B9 B8) 2)
    (= (move-distance B9 seederPos) 19)
    (= (move-distance B9 wateringnozzlePos) 18)
    (= (move-distance B9 weederPos) 17)
    (= (move-distance B9 soilsensorPos) 16)
    (= (move-distance B9 posSeedTray) 15)
    (= (move-distance B9 posBin) 14)
    (= (move-distance B9 home) 7)
    (= (move-distance seederPos A1) 5)
    (= (move-distance seederPos A2) 7)
    (= (move-distance seederPos A3) 9)
    (= (move-distance seederPos A4) 4)
    (= (move-distance seederPos A5) 6)
    (= (move-distance seederPos A6) 8)
    (= (move-distance seederPos A7) 9)
    (= (move-distance seederPos A8) 11)
    (= (move-distance seederPos A9) 13)
    (= (move-distance seederPos B1) 11)
    (= (move-distance seederPos B2) 13)
    (= (move-distance seederPos B3) 15)
    (= (move-distance seederPos B4) 10)
    (= (move-distance seederPos B5) 12)
    (= (move-distance seederPos B6) 14)
    (= (move-distance seederPos B7) 15)
    (= (move-distance seederPos B8) 17)
    (= (move-distance seederPos B9) 19)
    (= (move-distance seederPos wateringnozzlePos) 1)
    (= (move-distance seederPos weederPos) 2)
    (= (move-distance seederPos soilsensorPos) 3)
    (= (move-distance seederPos posSeedTray) 4)
    (= (move-distance seederPos posBin) 5)
    (= (move-distance seederPos home) 12)
    (= (move-distance wateringnozzlePos A1) 6)
    (= (move-distance wateringnozzlePos A2) 8)
    (= (move-distance wateringnozzlePos A3) 10)
    (= (move-distance wateringnozzlePos A4) 3)
    (= (move-distance wateringnozzlePos A5) 5)
    (= (move-distance wateringnozzlePos A6) 7)
    (= (move-distance wateringnozzlePos A7) 8)
    (= (move-distance wateringnozzlePos A8) 10)
    (= (move-distance wateringnozzlePos A9) 12)
    (= (move-distance wateringnozzlePos B1) 12)
    (= (move-distance wateringnozzlePos B2) 14)
    (= (move-distance wateringnozzlePos B3) 16)
    (= (move-distance wateringnozzlePos B4) 9)
    (= (move-distance wateringnozzlePos B5) 11)
    (= (move-distance wateringnozzlePos B6) 13)
    (= (move-distance wateringnozzlePos B7) 14)
    (= (move-distance wateringnozzlePos B8) 16)
    (= (move-distance wateringnozzlePos B9) 18)
    (= (move-distance wateringnozzlePos seederPos) 1)
    (= (move-distance wateringnozzlePos weederPos) 1)
    (= (move-distance wateringnozzlePos soilsensorPos) 2)
    (= (move-distance wateringnozzlePos posSeedTray) 3)
    (= (move-distance wateringnozzlePos posBin) 4)
    (= (move-distance wateringnozzlePos home) 11)
    (= (move-distance weederPos A1) 7)
    (= (move-distance weederPos A2) 9)
    (= (move-distance weederPos A3) 11)
    (= (move-distance weederPos A4) 2)
    (= (move-distance weederPos A5) 4)
    (= (move-distance weederPos A6) 6)
    (= (move-distance weederPos A7) 7)
    (= (move-distance weederPos A8) 9)
    (= (move-distance weederPos A9) 11)
    (= (move-distance weederPos B1) 13)
    (= (move-distance weederPos B2) 15)
    (= (move-distance weederPos B3) 17)
    (= (move-distance weederPos B4) 8)
    (= (move-distance weederPos B5) 10)
    (= (move-distance weederPos B6) 12)
    (= (move-distance weederPos B7) 13)
    (= (move-distance weederPos B8) 15)
    (= (move-distance weederPos B9) 17)
    (= (move-distance weederPos seederPos) 2)
    (= (move-distance weederPos wateringnozzlePos) 1)
    (= (move-distance weederPos soilsensorPos) 1)
    (= (move-distance weederPos posSeedTray) 2)
    (= (move-distance weederPos posBin) 3)
    (= (move-distance weederPos home) 10)
    (= (move-distance soilsensorPos A1) 8)
    (= (move-distance soilsensorPos A2) 10)
    (= (move-distance soilsensorPos A3) 12)
    (= (move-distance soilsensorPos A4) 3)
    (= (move-distance soilsensorPos A5) 5)
    (= (move-distance soilsensorPos A6) 7)
    (= (move-distance soilsensorPos A7) 6)
    (= (move-distance soilsensorPos A8) 8)
    (= (move-distance soilsensorPos A9) 10)
    (= (move-distance soilsensorPos B1) 14)
    (= (move-distance soilsensorPos B2) 16)
    (= (move-distance soilsensorPos B3) 18)
    (= (move-distance soilsensorPos B4) 9)
    (= (move-distance soilsensorPos B5) 11)
    (= (move-distance soilsensorPos B6) 13)
    (= (move-distance soilsensorPos B7) 12)
    (= (move-distance soilsensorPos B8) 14)
    (= (move-distance soilsensorPos B9) 16)
    (= (move-distance soilsensorPos seederPos) 3)
    (= (move-distance soilsensorPos wateringnozzlePos) 2)
    (= (move-distance soilsensorPos weederPos) 1)
    (= (move-distance soilsensorPos posSeedTray) 1)
    (= (move-distance soilsensorPos posBin) 2)
    (= (move-distance soilsensorPos home) 9)
    (= (move-distance posSeedTray A1) 9)
    (= (move-distance posSeedTray A2) 11)
    (= (move-distance posSeedTray A3) 13)
    (= (move-distance posSeedTray A4) 4)
    (= (move-distance posSeedTray A5) 6)
    (= (move-distance posSeedTray A6) 8)
    (= (move-distance posSeedTray A7) 5)
    (= (move-distance posSeedTray A8) 7)
    (= (move-distance posSeedTray A9) 9)
    (= (move-distance posSeedTray B1) 15)
    (= (move-distance posSeedTray B2) 17)
    (= (move-distance posSeedTray B3) 19)
    (= (move-distance posSeedTray B4) 10)
    (= (move-distance posSeedTray B5) 12)
    (= (move-distance posSeedTray B6) 14)
    (= (move-distance posSeedTray B7) 11)
    (= (move-distance posSeedTray B8) 13)
    (= (move-distance posSeedTray B9) 15)
    (= (move-distance posSeedTray seederPos) 4)
    (= (move-distance posSeedTray wateringnozzlePos) 3)
    (= (move-distance posSeedTray weederPos) 2)
    (= (move-distance posSeedTray soilsensorPos) 1)
    (= (move-distance posSeedTray posBin) 1)
    (= (move-distance posSeedTray home) 10)
    (= (move-distance posBin A1) 10)
    (= (move-distance posBin A2) 12)
    (= (move-distance posBin A3) 14)
    (= (move-distance posBin A4) 5)
    (= (move-distance posBin A5) 7)
    (= (move-distance posBin A6) 9)
    (= (move-distance posBin A7) 4)
    (= (move-distance posBin A8) 6)
    (= (move-distance posBin A9) 8)
    (= (move-distance posBin B1) 16)
    (= (move-distance posBin B2) 18)
    (= (move-distance posBin B3) 20)
    (= (move-distance posBin B4) 11)
    (= (move-distance posBin B5) 13)
    (= (move-distance posBin B6) 15)
    (= (move-distance posBin B7) 10)
    (= (move-distance posBin B8) 12)
    (= (move-distance posBin B9) 14)
    (= (move-distance posBin seederPos) 5)
    (= (move-distance posBin wateringnozzlePos) 4)
    (= (move-distance posBin weederPos) 3)
    (= (move-distance posBin soilsensorPos) 2)
    (= (move-distance posBin posSeedTray) 1)
    (= (move-distance posBin home) 11)
    (= (move-distance home A1) 13)
    (= (move-distance home A2) 11)
    (= (move-distance home A3) 9)
    (= (move-distance home A4) 8)
    (= (move-distance home A5) 6)
    (= (move-distance home A6) 4)
    (= (move-distance home A7) 11)
    (= (move-distance home A8) 9)
    (= (move-distance home A9) 7)
    (= (move-distance home B1) 7)
    (= (move-distance home B2) 7)
    (= (move-distance home B3) 9)
    (= (move-distance home B4) 2)
    (= (move-distance home B5) 2)
    (= (move-distance home B6) 4)
    (= (move-distance home B7) 5)
    (= (move-distance home B8) 5)
    (= (move-distance home B9) 7)
    (= (move-distance home seederPos) 12)
    (= (move-distance home wateringnozzlePos) 11)
    (= (move-distance home weederPos) 10)
    (= (move-distance home soilsensorPos) 9)
    (= (move-distance home posSeedTray) 10)
    (= (move-distance home posBin) 11)





)

(:goal (and

    ;todo: put the goal condition here
))

;un-comment the following line if metric is needed
(:metric minimize 
    (total-moving-cost)
    
    )
)
